version: '3.8'
services:

  invoke-receiver:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    image: dapr-test
    ports:
      - "50051:50051" # Dapr instances communicate over gRPC so we need to expose the gRPC port
      - "8080:8080"
    command: [ "/app/docker/docker-entrypoint.sh" ]
    depends_on:
      - redis
      - placement
    networks:
      - hello-dapr

  invoke-receiver-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "invoke-receiver",
      "--app-port", "50051",
      "--app-protocol", "grpc",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--config", "config.yaml",
      "--components-path", "./components"
    ]
    volumes:
        - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --components-path argument.
        - "./src/services/config.yaml:/config.yaml"
    depends_on:
      - invoke-receiver
    network_mode: "service:invoke-receiver" # Attach the nodeapp-dapr service to the nodeapp network namespace

################

  invoke-client:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    image: dapr-test
    deploy:
      replicas: 2
    # ports:
    #   - "50007:50007" # Dapr instances communicate over gRPC so we need to expose the gRPC port
    command: [
      "dapr", "run",
      "--app-id", "invoke-client",
      # "--app-port", "50007",
      # "--app-protocol", "grpc",
      "--config", "src/services/config.yaml",
      "--", 
      "pipenv", "run", "python", "-m", "src.services.client"
    ]
    depends_on:
      - invoke-receiver-dapr
    networks:
      - hello-dapr

  invoke-client-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
     "--app-id", "invoke-client",
    #  "--app-port", "50007",
    #  "--app-protocol", "grpc",
     "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
     "--config", "config.yaml",
     "--components-path", "./components"
     ]
    volumes:
        - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --components-path argument.
        - "./src/services/config.yaml:/config.yaml"
    depends_on:
      - invoke-client
    network_mode: "service:invoke-client" # Attach the nodeapp-dapr service to the nodeapp network namespace

############

  placement:
    image: "daprio/dapr:latest"
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"
      # - "9411:9411"
    networks:
      - hello-dapr

  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - hello-dapr

  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
    networks:
      - hello-dapr 
  
networks:
  hello-dapr: null